framework:
    messenger:
        transports:
            my_transport_sync:
                dsn: 'amqp://guest:guest@rabbitmq:5672'
                retry_strategy:
                    max_retries: 0
                options:
                    reply:
                        timeout: 5
                        prefix: 'my_reply_'
#                    reply: ~
                    exchange:
                        name: query_exchange
                        type: topic
                    queues:
                        query_queue: ~
        routing:
            'App\Query\MyQuery': my_transport_sync
